db:
  # path relative to _internal folder
  # default ../db
  path: ../db

llm:
  completion:
    # path relative to executable
    # model must be of "gguf" type
    model: ../<model>.gguf

    # does model require flash attention enabled?
    # default is false
    flash_attention: false

  embedding:
    # path relative to executable
    # model must be of "gguf" type and designed for embedding use
    model: ../<model>.gguf

    # context size / max input word supported by the model
    context: 256

    # vector size of the model
    size: 384
