[db]
# path relative from _internal folder
path = "../db"

[llm]
[llm.completion]
# path relative from executable. must be of "gguf" type
model = "../<model>.gguf"

# does model require flash attention? default is false
flash_attention = false

[llm.embedding]
# path relative from executable. must be of "gguf" type and for embedding use
model = "../<model>.gguf"

# context size / max input word supported by the model
context = 512

# vector size of the model
size = 384
